#ifndef ARCH_I386_LPC_KDB_H
#define ARCH_I386_LPC_KDB_H

/*Keyboard(8042, name=lpc_kbd)*/
enum kbd_controller_reg {
	KBD_OUTPUT_REG=0x60,
	KBD_INPUT_REG=0x60,
	KBD_STATUS_REG=0x64,
	KBD_COMMAND_REG=0x64,
	KBD_CONTROLLER_CONFIG_BYTE=0x61
};

#define KBD_CMD_DISABLE_KEYBOARD 0xAD
#define KBD_CMD_ENABLE_KEYBOARD 0xAE
#define KBD_CMD_READ_CONFIG_BYTE 0x20
#define KBD_CMD_WRITE_CONFIG_BYTE 0x60
#define KBD_CMD_SELF_TEST 0xAA
#define KBD_CMD_TEST_PORT 0xAB

#define FADT_SIGNATURE 0x50434146
#define FADT_IAPC_BOOT_ARCH_FLAGS_OFFSET 109
#define PS2_CONTROLLER_FLAG_BIT 1

#endif
